services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: citydb
      POSTGRES_USER: cityuser
      POSTGRES_PASSWORD: citypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      DJANGO_SETTINGS_MODULE: city_service.settings
      POSTGRES_DB: citydb
      POSTGRES_USER: cityuser
      POSTGRES_PASSWORD: citypass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/code
    working_dir: /code
    command: celery -A city_service worker -l info
    depends_on:
      - db
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      DJANGO_SETTINGS_MODULE: city_service.settings
      POSTGRES_DB: citydb
      POSTGRES_USER: cityuser
      POSTGRES_PASSWORD: citypass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/code
    working_dir: /code
    command: celery -A city_service beat -l info
    depends_on:
      - db
      - redis

volumes:
  pgdata:
